name: Publish a Wasm Component to GitHub Artifacts

on:
  push:
    tags:
      - v*
  workflow_dispatch:

env:
  IMAGE_NAME: ${{ github.repository }}

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{ github.actor }}/rust-wasi-hello
          tags: |
            type=semver,pattern={{version}}
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Cache cargo bin
        id: cache-cargo
        uses: actions/cache@v3
        env:
          cache-name: cache-cargo-bin
        with:
          path: ~/.cargo/bin
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('scripts/install.sh') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-

      - if: ${{ steps.cache-cargo.outputs.cache-hit != 'true' }}
        name: Run install script
        continue-on-error: false
        run: bash scripts/install.sh

      - name: Run build script
        run: bash scripts/build.sh

      - name: Run publish script
        run: bash scripts/publish.sh ${{ fromJSON(steps.meta.outputs.json).labels['org.opencontainers.image.version'] }}

      - name: Install Cosign
        uses: sigstore/cosign-installer@v3.7.0

      - name: Sign wasm component
        run: |
          image="ghcr.io/${{ github.actor }}/rust-wasi-hello:${{ fromJSON(steps.meta.outputs.json).labels['org.opencontainers.image.version'] }}"
          cosign sign --yes --key env://COSIGN_PRIVATE_KEY $image
        env:
          COSIGN_PRIVATE_KEY: ${{ secrets.COSIGN_PRIVATE_KEY }}
          COSIGN_PASSWORD: ${{ secrets.COSIGN_PASSWORD }}
